root = "."
tmp_dir = "tmp"

[build]
	cmd = "go build -o ./tmp/main ./"
	bin = "tmp/main"
	include_ext = ["go"]
	exclude_dir = ["tmp", "frontend", "node_modules"]
	delay = 100
	stop_on_error = true

[log]
	time = true

[color]
	main = "yellow"
	watcher = "cyan"
	build = "green"
	runner = "magenta"

[misc]
	clean_on_exit = true